name: Release build

on:
    release:
        types: [created]

jobs:
    upload-release:
        name: Upload release
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Get release
              id: get_release
              uses: bruceadams/get-release@v1.2.3
              env:
                  GITHUB_TOKEN: ${{ github.token }}

            - uses: actions/download-artifact@v2
              id: download
              with:
                  name: build
                  path: ./mod/build/bundle.js

            - name: Upload build to release
              uses: actions/upload-release-asset@v1.0.2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.get_release.outputs.upload_url }}
                  asset_path: ${{steps.download.outputs.download-path}}
                  asset_name: ${{ steps.get_release.outputs.tag_name }}.js
                  asset_content_type: application/javascript
    build:
        name: Building mod
        runs-on: ubuntu-latest

        steps:
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: "10.x"

            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Install Yarn Dependencies
              run: |
                  cd mod/
                  yarn
            - name: Build
              run: |
                  cd mod/
                  yarn build
            - name: Upload artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: build
                  path: ./mod/build/bundle.js
