name: Release build

on:
    release:
        types: [created]

jobs:
    upload-release:
        name: Upload release
        runs-on: ubuntu-latest
        needs: build
        if: 0 == 1

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Get release
              id: get_release
              uses: bruceadams/get-release@v1.2.3
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Get upload url
              uses: actions/github-script@0.9.0
              id: upload_url
              env:
                  upload_url: ${{ steps.get_release.outputs.upload_url }}
              with:
                  script: |
                      core.setOutput('upload_url', process.env.upload_url.slice(0, -13))

            - name: Download artifacts
              uses: actions/download-artifact@v2
              id: download
              with:
                  name: build
                  path: ./mod/build/

            - name: Check dir
              run: ls -R

            - name: Upload build to release
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.upload_url.outputs.upload_url }}
                  asset_path: ./mod/build/bundle.js
                  asset_name: ${{ steps.get_release.outputs.tag_name }}.js
                  asset_content_type: application/javascript
    build:
        name: Building mod
        runs-on: ubuntu-latest

        steps:
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: "10.x"

            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Install Yarn Dependencies
              run: |
                  cd mod/
                  yarn
            - name: Build
              run: |
                  cd mod/
                  yarn build
            - name: Upload artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: build
                  path: ./mod/build/bundle.js
            - name: Check dir
              run: ls -R

            - name: Get release
              id: get_release
              uses: bruceadams/get-release@v1.2.3
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Get upload url
              uses: actions/github-script@0.9.0
              id: upload_url
              env:
                  upload_url: ${{ steps.get_release.outputs.upload_url }}
              with:
                  script: |
                      core.setOutput('upload_url', process.env.upload_url.slice(0, -13))

            - name: Upload build to release
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.upload_url.outputs.upload_url }}
                  asset_path: ./mod/build/bundle.js
                  asset_name: ${{ steps.get_release.outputs.tag_name }}.js
                  asset_content_type: application/javascript
